# Site
name: "Zen"
description: "My writing is an exercise in respect for your time. :)"
meta_description: "A blog designed and written by Siddharth Sham"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.png'
baseurl: /
google_analytics: 'UA-123602210-1'
disqus: 'Zen'
mailchimp-list: ''

# Authors
authors:
  sid:
    name: Siddharth Sham
    display_name: Siddharth Sham
    email: siddhsham@gmail.com
    web: https://siddharthsham.github.io/zen
    description: "Me? I'm probably drinking coffee, as I dream about alternate Universes in which blog pages type themselves..."
    instagram: https://www.instagram.com/Siddharth_Sham
    gravatar: 'assets/images/profile.jpg'

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-archives
  - jekyll-pwa-plugin

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# PWA
pwa:
  sw_src_filepath: /sw.js # Optional
  sw_dest_filename: /sw.js # Optional
  dest_js_directory: assets/js # Required
  precache_recent_posts_num: 5 # Optional
  precache_glob_directory: / # Optional
  precache_glob_patterns: # Optional
    - "{js,css,fonts}/**/*.{js,css,eot,svg,ttf,woff}"
    - index.html
  precache_glob_ignores: # Optional
    - sw-register.js
    - "fonts/**/*"

# Other
markdown: kramdown
highlighter: rouge
