# Site
name: "Zen"
description: "My writing is an exercise in respect for your time. :)"
meta_description: "A blog designed and written by Siddharth Sham"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.png'
baseurl: /
google_analytics: 'UA-123602210-1'
disqus: 'Zen'
mailchimp-list: ''

# Authors
authors:
  sid:
    name: Siddharth Sham
    display_name: Siddharth Sham
    email: siddhsham@gmail.com
    web: https://siddharthsham.github.io/zen
    description: "Me? I'm probably drinking coffee, as I dream about alternate Universes in which blog pages type themselves..."
    instagram: https://www.instagram.com/Siddharth_Sham
    gravatar: 'assets/images/profile.jpg'

gems: ['jekyll-offline']

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-archives
  - jekyll-offline

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown
highlighter: rouge
